### ISSUE TITLE
Empty Div, no share buttons visible

### ISSUE THREAD

**Issue by jleaders** [ayozehd/sharer#1]
I installed the plugin, enabled twig processing, and inserted `{{ sharer() }}` into my blog's item, but the output was just an empty div:
```
<div class="sharer-buttons-toolbar clearfix ">
        </div>

```
Did I miss a step?

**Comment by ayozehd** [comment]
In short `sharer()` function loop `buttons` from plugin configuration. In your `sharer.yml` file, how's your `buttons:` array parameter? Is it empty?
If not probably there's a problem with caches. I'll do an update next days to ignore cache and also fix other bugs I found.

**Comment by jleaders** [comment]
I have Facebook enabled at least, and I did hit the "Clear Cache" button on the far left of the admin panel
![plugins](https://user-images.githubusercontent.com/2430917/65548134-bf43d100-decf-11e9-98e0-6b3cb7f9a9f6.png)

**Comment by ayozeglaboo** [comment]
I haven't been able to reproduce your bug. There's a new release [1.1](https://github.com/ayozehd/grav-plugin-sharer/releases/tag/1.1) which doesn't store anything in cache because it wasn't necessary. Grav already cache all plugins and theme configurations into PHP objects.

Let me know if that update fixed your issue. Otherwise I will need more information about your other installed plugins, system, grav options, etc.

**Comment by ayozehd** [comment]
I haven't been able to reproduce your bug. There's a new release [1.1](https://github.com/ayozehd/grav-plugin-sharer/releases/tag/1.1) which doesn't store anything in cache because it wasn't necessary. Grav already cache all plugins and theme configurations into PHP objects.

Let me know if that update fixed your issue. Otherwise I will need more information about your other installed plugins, system, grav options, etc.

**Comment by jleaders** [comment]
That didn't fix it, I updated grav & the plugin and cleared the cache. I'll dig around the yml's and get a little more in depth and circle back with what I find.

**Comment by ayozehd** [comment]
Long time ago since you found this error... Latest release [1.2.2](https://github.com/ayozehd/grav-plugin-sharer/releases/tag/1.2.2) doesn't solve your 'empty div' yet?

**Comment by jleaders** [comment]
I ran the plugin updater, and still no luck. If you look at the [source](https://jonnyleaders.com/gaming/ashe) here, this is all that comes out:
```
<div class="sharer-buttons-toolbar clearfix ">
    </div>  
```

**Comment by jleaders** [comment]
I was in a reverse proxy so it was trying to connect to `localhost`. I fixed it by setting `custom_base_url` to https://example.com in user/config/system.yaml
